import { Car, CarType, FuelType } from './types';

export const LOCATIONS = [
  "New York, NY",
  "Los Angeles, CA",
  "Miami, FL",
  "San Francisco, CA",
  "Chicago, IL",
  "Austin, TX",
  "Seattle, WA"
];

export const CARS: Car[] = [
  {
    id: 'c1',
    brand: 'Tesla',
    model: 'Model 3',
    year: 2024,
    type: CarType.ELECTRIC,
    fuel: FuelType.ELECTRIC,
    transmission: 'Automatic',
    seats: 5,
    pricePerDay: 89,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1536700503339-1e4205892bbe?auto=format&fit=crop&q=80&w=800',
    location: 'Los Angeles, CA',
    features: ['Autopilot', 'GPS', 'Bluetooth', 'Heated Seats'],
    available: true
  },
  {
    id: 'c2',
    brand: 'Toyota',
    model: 'Camry',
    year: 2023,
    type: CarType.SEDAN,
    fuel: FuelType.HYBRID,
    transmission: 'Automatic',
    seats: 5,
    pricePerDay: 55,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1621007947382-bb3c3968e3bb?auto=format&fit=crop&q=80&w=800',
    location: 'New York, NY',
    features: ['Bluetooth', 'Rear Camera', 'Apple CarPlay'],
    available: true
  },
  {
    id: 'c3',
    brand: 'Mercedes-Benz',
    model: 'C-Class',
    year: 2023,
    type: CarType.LUXURY,
    fuel: FuelType.PETROL,
    transmission: 'Automatic',
    seats: 5,
    pricePerDay: 120,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&q=80&w=800',
    location: 'Miami, FL',
    features: ['Leather Seats', 'Sunroof', 'Premium Sound', '360 Camera'],
    available: true
  },
  {
    id: 'c4',
    brand: 'Ford',
    model: 'Mustang GT',
    year: 2022,
    type: CarType.SPORTS,
    fuel: FuelType.PETROL,
    transmission: 'Automatic',
    seats: 4,
    pricePerDay: 145,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1584345604476-8ec5e12e42dd?auto=format&fit=crop&q=80&w=800',
    location: 'Los Angeles, CA',
    features: ['V8 Engine', 'Convertible', 'Sport Mode'],
    available: true
  },
  {
    id: 'c5',
    brand: 'BMW',
    model: 'X5',
    year: 2024,
    type: CarType.SUV,
    fuel: FuelType.DIESEL,
    transmission: 'Automatic',
    seats: 7,
    pricePerDay: 110,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1556189250-72ba95452242?auto=format&fit=crop&q=80&w=800',
    location: 'Chicago, IL',
    features: ['All-Wheel Drive', 'Panoramic Roof', 'Leather Interior'],
    available: true
  },
  {
    id: 'c6',
    brand: 'Honda',
    model: 'Civic',
    year: 2022,
    type: CarType.ECONOMY,
    fuel: FuelType.PETROL,
    transmission: 'Automatic',
    seats: 5,
    pricePerDay: 45,
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&q=80&w=800',
    location: 'Austin, TX',
    features: ['Bluetooth', 'Efficient', 'Lane Assist'],
    available: true
  },
  {
    id: 'c7',
    brand: 'Jeep',
    model: 'Wrangler',
    year: 2023,
    type: CarType.SUV,
    fuel: FuelType.PETROL,
    transmission: 'Automatic',
    seats: 5,
    pricePerDay: 95,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&q=80&w=800',
    location: 'Seattle, WA',
    features: ['4x4', 'Removable Top', 'Off-road Tires'],
    available: true
  },
  {
    id: 'c8',
    brand: 'Porsche',
    model: '911 Carrera',
    year: 2024,
    type: CarType.SPORTS,
    fuel: FuelType.PETROL,
    transmission: 'Automatic',
    seats: 2,
    pricePerDay: 250,
    rating: 5.0,
    image: 'https://images.unsplash.com/photo-1503376763036-066120622c74?auto=format&fit=crop&q=80&w=800',
    location: 'Miami, FL',
    features: ['Sport Chrono', 'Leather', 'Turbo'],
    available: true
  },
  {
    id: 'c9',
    brand: 'Hyundai',
    model: 'Ioniq 5',
    year: 2024,
    type: CarType.ELECTRIC,
    fuel: FuelType.ELECTRIC,
    transmission: 'Automatic',
    seats: 5,
    pricePerDay: 85,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1670353457199-63799a4e39b3?auto=format&fit=crop&q=80&w=800',
    location: 'San Francisco, CA',
    features: ['Fast Charging', 'Modern Tech', 'Spacious'],
    available: true
  }
];
